groups:
  - docker: [ubuntu]
apt:
 - 
write_files:
 - path: /tmp/docker.sh
   permissions: 0744
   owner: root
   content: |
     #!/usr/bin/env bash
     echo \
     "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
 - path: /tmp/prep.sh
   permissions: 0744
   owner: root
   content: |
     #!/usr/bin/env bash
     cd ~ubuntu
     git clone https://github.com/Azure/sonic-buildimage.git
     sed -i 's/SONIC_CONFIG_BUILD_JOBS = 1/SONIC_CONFIG_BUILD_JOBS = 4/g' sonic-buildimage/rules/config
     sed -i 's/DEFAULT_PASSWORD = YourPaSsWoRd/DEFAULT_PASSWORD = admin/g' sonic-buildimage/rules/config
     sed -i 's/# SHUTDOWN_BGP_ON_START = y/SHUTDOWN_BGP_ON_START = n/g' sonic-buildimage/rules/config
     chown -R ubuntu sonic-buildimage

     
packages:
 - ca-certificates
 - curl
 - gnupg
 - lsb-release
 - python3-pip
 - j2cli
runcmd:
 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
 - bash /tmp/docker.sh
 - sudo apt-get -y update
 - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
 - git clone https://github.com/Azure/sonic-buildimage.git
 - modprobe overlay
 - /tmp/prep.sh
